name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish-native:
    name: Publish ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container || '' }}

    permissions:
      id-token: write
      contents: read

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - os: ubuntu-latest
            name: linux-x64
            platform: linux
            arch: x64

          - os: ubuntu-latest
            name: linux-arm64
            platform: linux
            arch: arm64

          - os: ubuntu-latest
            name: linux-musl-x64
            platform: linux
            arch: x64
            libc: musl
            container: node:24-alpine

          - os: ubuntu-latest
            name: linux-musl-arm64
            platform: linux
            arch: arm64
            libc: musl
            container: node:24-alpine

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Install build tools (musl)
        if: contains(matrix.name, 'musl')
        run: apk add --no-cache python3 make g++ linux-headers

      - run: npm i --no-fund --no-audit

      - name: Build native
        run: npm run build:native

      - name: Generate package
        env:
          TARGET_PLATFORM: ${{ matrix.platform }}
          TARGET_ARCH: ${{ matrix.arch }}
          TARGET_LIBC: ${{ matrix.libc || '' }}
        run: node scripts/package-native.ts "$TARGET_PLATFORM" "$TARGET_ARCH" "$TARGET_LIBC"

      - name: Publish
        working-directory: pkg
        run: npm publish --access public

  publish-main:
    needs: publish-native
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - run: npm i --no-fund --no-audit
      - run: npm run build:js

      - run: npm publish --access public
